### ISSUE TITLE
[Bug]: github同步报错

### ISSUE THREAD

**Issue by Natsume-Shiki** [ximu3/vnite#12]
### 软件版本

1.1.0

### 问题描述

登录账号点同步会报错，这应该不是网络问题吧，挂梯子也没用

### 问题日志

[2024-09-05 20:41:12.530] [info]  正在拉取远程更改...
[2024-09-05 20:41:12.535] [error] Github同步失败： Error: Error: spawn git ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Object.action (file:///D:/galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///D:/galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///D:/galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///D:/galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///D:/galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)

**Comment by ximu3** [comment]
请尝试退出账号后重新登录
