### ISSUE TITLE
[Bug]: 鼠标点击部分无响应

### ISSUE THREAD

**Issue by Cynice** [ximu3/vnite#16]
https://github.com/user-attachments/assets/d420b81c-f9ef-40ae-899b-2b5dea7117c4

**Comment by ximu3** [comment]
请问是全新安装还是更新，现在的版本是多少呢？

**Comment by Cynice** [comment]
全新版本的，然后我降级了也不行，一开始是登录并关联github了的。然后关应用了再打开，点击就无反应了，卸载重装也不行。

（不知道软件的数据文件在哪个文件夹，删了应该可以了，或者有什么别的解决办法）

**Comment by Cynice** [comment]
![b90c8f5b-f44b-4cde-b3b5-446d35425344](https://github.com/user-attachments/assets/eb287274-f5c0-4e7b-925b-130ab5548c32)

v1.2.2和v1.2.1

**Comment by ximu3** [comment]
之前是否进行过云同步呢（1.2.2之前的旧版本）

**Comment by ximu3** [comment]
数据文件在 C:\Users\你的用户名\AppData\Roaming\vnite\app\ 下
可以尝试删除app文件夹，然后重新安装最新版本
可以贴一下 C:\Users\你的用户名\AppData\Roaming\vnite\app\config\config.json的内容，记得对accessToken进行隐私处理！

**Comment by Cynice** [comment]
仅在1.2.2云同步过

**Comment by Cynice** [comment]
![image](https://github.com/user-attachments/assets/ef885ab7-cea9-428c-9470-03ceb0b1ffa3)
无\config\config.json的内容

**Comment by ximu3** [comment]
应用根目录有log，麻烦贴一下

**Comment by ximu3** [comment]
如果你已经重新安装，请在登录github账号后选择使用本地数据

**Comment by Cynice** [comment]
我把Roaming的vnite删了，看不了log了，目前可以同步了

**Comment by ximu3** [comment]
ok，感谢您的反馈。

**Comment by Cynice** [comment]
![image](https://github.com/user-attachments/assets/8aa52d9f-3e69-416d-b7d5-748d2a0cf728)
现在，同步之后关掉应用再开启又这样了，点不了了

**Comment by Cynice** [comment]
![image](https://github.com/user-attachments/assets/f7d57131-4420-4708-8c9a-2ad19e1dc8bf)
log

**Comment by ximu3** [comment]
config.json是不是又消失了

**Comment by Cynice** [comment]
![image](https://github.com/user-attachments/assets/9e57e260-1bd7-4de9-af55-82faadfe6413)
空的

**Comment by ximu3** [comment]
登录github账号后是选择使用本地数据的吗

**Comment by Cynice** [comment]
忘了，在哪看

**Comment by ximu3** [comment]
> ![image](https://private-user-images.githubusercontent.com/181150097/366303420-f7d57131-4420-4708-8c9a-2ad19e1dc8bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzA5MjYsIm5iZiI6MTcyNjAzMDYyNiwicGF0aCI6Ii8xODExNTAwOTcvMzY2MzAzNDIwLWY3ZDU3MTMxLTQ0MjAtNDcwOC04YzlhLTJhZDE5ZTFkYzhiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwNDU3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjY1MDQzMjc2Y2MyNzJmZmQ4MmVjMTcwYTZmZjBkNmFjZDkyMWI5MjI4OTRiMTVkMmI5OGM5YWZhNmEzOGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pZh5U5FlnyndbOHocPEpe3j4Ip5IvKbToP8XZE89VFk) log

不是main.log 是app.log

**Comment by ximu3** [comment]
vnite应用根目录\logs\app.log

**Comment by Cynice** [comment]
![image](https://github.com/user-attachments/assets/b4cca1ae-b061-4aae-8545-153a52a246c4)
无

**Comment by ximu3** [comment]
> vnite应用根目录

是在vnite应用根目录

**Comment by ximu3** [comment]
![image](https://github.com/user-attachments/assets/959ac4dd-9781-4ce9-970a-50fbdee6d235)

**Comment by Cynice** [comment]
[2024-09-11 12:47:41.048] [info]  App started 应用已启动
[2024-09-11 12:48:44.729] [info]  App started 应用已启动
[2024-09-11 12:48:45.848] [info]  游戏数据已成功更新
[2024-09-11 12:48:45.855] [info]  设置已成功更新
[2024-09-11 12:48:51.137] [info]  Github认证成功: {

[2024-09-11 12:48:51.143] [info]  设置已成功更新
[2024-09-11 12:48:51.813] [error] 初始化仓库时出错: Error: Error: spawn git ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Object.action (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
[2024-09-11 12:48:57.347] [error] 更新设置时出错: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\config\config.json'
[2024-09-11 12:48:57.348] [error] Unhandled rejection Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\config\config.json'
[2024-09-11 12:49:02.174] [error] WebDav同步（下载）失败： TypeError [ERR_INVALID_URL]: Invalid URL
    at NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:642:13)
    at new Request (file:///D:/vnite/vnite/resources/app.asar/node_modules/node-fetch/src/request.js:55:16)
    at file:///D:/vnite/vnite/resources/app.asar/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/vnite/vnite/resources/app.asar/node_modules/node-fetch/src/index.js:49:9)
    at __executeSequence (file:///D:/vnite/vnite/resources/app.asar/node_modules/hot-patcher/dist/functions.js:10:30)
    at HotPatcher.execute (file:///D:/vnite/vnite/resources/app.asar/node_modules/hot-patcher/dist/patcher.js:74:16)
    at HotPatcher.patchInline (file:///D:/vnite/vnite/resources/app.asar/node_modules/hot-patcher/dist/patcher.js:168:21)
    at file:///D:/vnite/vnite/resources/app.asar/node_modules/webdav/dist/node/request.js:132:64
[2024-09-11 12:49:08.584] [error] 更新设置时出错: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\config\config.json'
[2024-09-11 12:49:08.584] [error] Unhandled rejection Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\config\config.json'
[2024-09-11 12:49:08.591] [error] 操作过程中出错: Error: Error: spawn git ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Object.action (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
[2024-09-11 12:49:08.591] [error] 同步云端数据时出错: Error: Error: spawn git ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Object.action (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
[2024-09-11 12:49:08.593] [error] Error: Error invoking remote method 'pull-changes': Error: Error: spawn git ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-09-11 12:50:24.067] [info]  正在拉取远程更改...
[2024-09-11 12:50:24.071] [error] Github同步失败： Error: Error: spawn git ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Object.action (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/vnite/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
[2024-09-11 12:50:24.072] [info]  应用已退出
[2024-09-11 12:52:54.627] [info]  App started 应用已启动
[2024-09-11 12:52:55.710] [error] Error reading JSON file: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\data\data.json'
[2024-09-11 12:52:55.711] [error] Error reading JSON file: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\config\config.json'
[2024-09-11 12:52:55.711] [error] Error reading JSON file: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\data\categories.json'
[2024-09-11 12:52:55.717] [error] 更新游戏数据时出错: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\data\data.json'
[2024-09-11 12:56:23.737] [info]  应用已退出
[2024-09-11 12:59:15.486] [info]  App started 应用已启动
[2024-09-11 12:59:16.543] [error] Error reading JSON file: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\data\data.json'
[2024-09-11 12:59:16.544] [error] Error reading JSON file: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\config\config.json'
[2024-09-11 12:59:16.544] [error] Error reading JSON file: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\data\categories.json'
[2024-09-11 12:59:16.576] [error] 更新游戏数据时出错: Error: ENOENT: no such file or directory, open 'C:\Users\Cynice\AppData\Roaming\vnite\app\data\data.json'
[2024-09-11 12:59:30.397] [info]  应用已退出
________________________________
发件人: ximu ***@***.***>
发送时间: 2024年9月11日 13:01
收件人: ximu3/vnite ***@***.***>
抄送: Cynice ***@***.***>; Author ***@***.***>
主题: Re: [ximu3/vnite] [Bug]: 鼠标点击部分无响应 (Issue #16)


image.png (view on web)<https://github.com/user-attachments/assets/959ac4dd-9781-4ce9-970a-50fbdee6d235>

―

**Comment by ximu3** [comment]
网络问题，请完全重新安装（删除c盘数据文件夹）后挂梯子后再登录github，抱歉我没考虑到这种情况会造成软件崩溃，我会尽快修复。

**Comment by ximu3** [comment]
webdav云同步现在是测试阶段，bug很多，不推荐使用

**Comment by Cynice** [comment]
我一直开着梯子

**Comment by ximu3** [comment]
github云同步功能是需要电脑自带git的
https://git-scm.com/download/win
请安装这个软件然后重试，麻烦您了

**Comment by Cynice** [comment]
这个怎么用？安装好后就不用管它了吗
________________________________
发件人: ximu ***@***.***>
发送时间: 2024年9月11日 20:00
收件人: ximu3/vnite ***@***.***>
抄送: Cynice ***@***.***>; Author ***@***.***>
主题: Re: [ximu3/vnite] [Bug]: 鼠标点击部分无响应 (Issue #16)


github云同步功能是需要电脑自带git的
https://git-scm.com/download/win
请安装这个软件然后重试，麻烦您了

―

**Comment by ximu3** [comment]
安装好了就不用管了，重装vnite即可

**Comment by Cynice** [comment]
好的
________________________________
发件人: ximu ***@***.***>
发送时间: 2024年9月11日 20:08
收件人: ximu3/vnite ***@***.***>
抄送: Cynice ***@***.***>; Author ***@***.***>
主题: Re: [ximu3/vnite] [Bug]: 鼠标点击部分无响应 (Issue #16)


安装好了就不用管了，重装vnite即可

―

**Comment by ximu3** [comment]
请问问题解决了吗，还是说又出现了新的bug🤣

**Comment by Cynice** [comment]
不行的，删除文件存档后，重装，启动，登录github后关闭依旧退出登录了，无法按登录。
![image](https://github.com/user-attachments/assets/3e0934ef-ccbf-4e8d-b0fe-e5fa5db29550)

**Comment by ZKENSS** [comment]
@ximu3 更新完，《开始启动》按钮点不动了……

**Comment by ximu3** [comment]
> @ximu3 [2024-09-11 22:48:15.689] [info] App started 应用已启动 [2024-09-11 22:48:15.959] [error] Error reading JSON file: Error: ENOENT: no such file or directory, open 'C:\Users\Zken\AppData\Roaming\vnite\app\config\config.json' [2024-09-11 22:48:15.989] [info] 游戏数据已成功更新

版本号，更新还是全新安装

**Comment by ZKENSS** [comment]
> 
> 版本号，更新还是全新安装

1.2.5.，更新后，启动失败了。重装后，启动还是失败@ximu3

**Comment by ximu3** [comment]
云同步现在会有很大几率导致数据损坏，请勿使用。

**Comment by ZKENSS** [comment]
> > > 版本号，更新还是全新安装
> > 
> > 1.2.5.，更新后，启动失败了。重装后，启动还是失败@ximu3
> 
> 关闭云同步，删除数据文件夹（C:\Users\你的用户名\AppData\Roaming\vnite 下的app文件夹），重新安装

**解决了**

**Comment by ximu3** [comment]
> 不行的，删除文件存档后，重装，启动，登录github后关闭依旧退出登录了，无法按登录。 ![image](https://private-user-images.githubusercontent.com/181150097/366486081-3e0934ef-ccbf-4e8d-b0fe-e5fa5db29550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDMyMjQsIm5iZiI6MTcyNjE0MjkyNCwicGF0aCI6Ii8xODExNTAwOTcvMzY2NDg2MDgxLTNlMDkzNGVmLWNjYmYtNGU4ZC1iMGZlLWU1ZmE1ZGIyOTU1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMjA4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzdjZjYyMzc2OWFhZmYxZTA0NDk3MzEzMjM1N2QyYTE5YTJjYmQyOTZkZWZhYjZjMzQzZDZhYjhlY2Q3MDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1-SUISA4J9RxadG2RRHrZcLp23l1oHZjkfBEwGPuDYA)

新版本重构了Github云同步，还请更新版本测试下。（最好是全新安装）

**Comment by ximu3** [comment]
非常感谢您认真与耐心的反馈和测试，我会继续优化vnite。
