### ISSUE TITLE
[Bug]: 操作失败没有跳出机制

### ISSUE THREAD

**Issue by angeruko** [ximu3/vnite#4]
### 软件版本

1.0.5

### 问题描述

游戏是 死神之吻乃离别之外  10年的老游戏
游戏一拉取，就报错了

### 问题日志

[2024-08-27 14:54:41.453] [error] 操作失败，1秒后重试。剩余重试次数：2 TypeError: Cannot read properties of undefined (reading 'game')
[2024-08-27 14:54:42.455] [error] 操作失败，1秒后重试。剩余重试次数：1 TypeError: Cannot read properties of undefined (reading 'game')
[2024-08-27 14:54:43.468] [error] 操作失败，1秒后重试。剩余重试次数：0 TypeError: Cannot read properties of undefined (reading 'game')
[2024-08-27 14:54:44.479] [error] Error in organizeGameData: TypeError: Cannot read properties of undefined (reading 'game')
    at file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:266:60
    at retry$2 (file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:128:18)
    at retry$2 (file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:135:14)
    at async organizeGameData (file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:266:17)
    at async IpcMainImpl.<anonymous> (file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:1086:5)
[2024-08-27 14:54:44.480] [error] Unhandled rejection TypeError: Cannot read properties of undefined (reading 'game')
    at file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:266:60
    at retry$2 (file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:128:18)
    at retry$2 (file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:135:14)
    at async organizeGameData (file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:266:17)
    at async IpcMainImpl.<anonymous> (file:///D:/Program%20Files/vnite/resources/app.asar/out/main/index.mjs:1086:5)
[2024-08-27 14:54:44.578] [info]  New game data has been added successfully

### 问题截图

![QQ截图20240827150206](https://github.com/user-attachments/assets/40a002ae-9a0e-4b24-a684-e64279638a4d)

**Comment by ximu3** [comment]
网络问题，可尝试更换网络环境（挂个梯子什么的）。跳出机制下个小版本就加。

**Comment by ximu3** [comment]
已增加跳出机制，更新版本即可。
