### ISSUE TITLE
[Bug]: （其实我不太确定这个是不是bug）存档转移问题

### ISSUE THREAD

**Issue by liuweixu** [ximu3/vnite#55]
### 软件版本

v1.5.8

### 问题描述

如果每次vnite玩gal后，会出现一个存档，并且复制到到相应的github上传地方，应该是这个流程，但是现在我发现有时会出现转移后的存档未必是这个游戏，而很有可能是上一次游戏存档的问题（然而logs记录是这个游戏，实质上是上一个游戏存档），甚至也会出现转移后的存档是空白的，所以我不得不删除这个存档，并且重新打开游戏，这样转移后的存档才会是这个游戏的存档。

### 问题日志

转以后存档是上一个游戏：
[2024-10-12 08:52:43.153] [info]  打开文件夹: E:\Japanese\GAL\暁WORKS\るいは智を呼ぶCOLLECTION\るいは智を呼ぶ\ゲーム\るいは智を呼ぶ\savedata
[2024-10-12 08:53:48.009] [info]  打开文件夹: E:\Japanese\GAL\暁WORKS\るいは智を呼ぶCOLLECTION\るいは智を呼ぶ\ゲーム\るいは智を呼ぶ\savedata
[2024-10-12 08:54:09.983] [info]  成功打开游戏 966824308
[2024-10-12 08:54:42.304] [info]  游戏数据已成功更新
[2024-10-12 08:54:42.307] [info]  成功复制游戏 966824308 存档到 C:\Users\weixu\AppData\Roaming\vnite\app\data\games\966824308\saves\1\
[2024-10-12 08:54:45.492] [info]  打开文件夹: C:\Users\weixu\AppData\Roaming\vnite\app\data\games\966824308
[2024-10-12 08:54:53.644] [info]  成功删除游戏 966824308 存档 1
[2024-10-12 08:54:53.660] [info]  游戏数据已成功更新
[2024-10-12 08:54:57.084] [info]  成功打开游戏 966824308
[2024-10-12 08:55:08.177] [info]  游戏数据已成功更新
[2024-10-12 08:55:08.188] [info]  成功复制游戏 966824308 存档到 C:\Users\weixu\AppData\Roaming\vnite\app\data\games\966824308\saves\1\
[2024-10-12 08:55:11.207] [info]  打开文件夹: C:\Users\weixu\AppData\Roaming\vnite\app\data\games\966824308
转移后存档是空白：
[2024-10-12 11:31:19.277] [info]  游戏数据已成功更新
[2024-10-12 11:31:19.343] [info]  游戏数据已成功更新
[2024-10-12 11:31:26.900] [info]  Path data successfully updated
[2024-10-12 11:31:30.221] [info]  成功打开游戏 223675113
[2024-10-12 11:31:56.486] [error] 复制游戏 223675113 存档时出错: Error: ENOENT: no such file or directory, lstat ''
[2024-10-12 11:31:56.505] [info]  游戏数据已成功更新
[2024-10-12 11:32:01.248] [info]  打开文件夹: C:\Users\weixu\AppData\Roaming\vnite\app\data\games\223675113
[2024-10-12 11:32:08.911] [info]  成功删除游戏 223675113 存档 1
[2024-10-12 11:32:08.923] [info]  游戏数据已成功更新
[2024-10-12 11:32:11.446] [info]  打开文件夹: C:\Users\weixu\AppData\Roaming\vnite\app\data\games\223675113
[2024-10-12 11:32:15.220] [info]  成功打开游戏 223675113

**Comment by ximu3** [comment]
对应的同步问题修复后这个问题应该也被修复了，还请更新测试下。

**Comment by liuweixu** [comment]
> 对应的同步问题修复后这个问题应该也被修复了，还请更新测试下。

您好，这个问题解决了，但是出现了新的问题，即不能自动云同步，每次产生新的存档文件时候，vnite就不能同步，log错误记录为：

[2024-10-12 16:25:01.484] [info]  成功打开游戏 134110077
[2024-10-12 16:25:14.774] [info]  游戏数据已成功更新
[2024-10-12 16:25:15.233] [info]  成功复制游戏 134110077 存档到 C:\Users\weixu\AppData\Roaming\vnite\app\data\games\134110077\saves\2\
[2024-10-12 16:25:15.793] [info]  本地同步完成，app -> sync
[2024-10-12 16:25:15.883] [error] Github同步失败： Error: fatal: not a git repository (or any of the parent directories): .git

    at Object.action (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-10-12 16:25:19.380] [info]  游戏数据已成功更新
[2024-10-12 16:25:19.426] [info]  游戏数据已成功更新
[2024-10-12 16:25:19.636] [info]  游戏数据已成功更新
[2024-10-12 16:25:19.894] [info]  游戏数据已成功更新
[2024-10-12 16:25:24.847] [info]  打开文件夹: C:\Users\weixu\AppData\Roaming\vnite\app\data\games\134110077
[2024-10-12 16:25:32.749] [info]  本地同步完成，app -> sync
[2024-10-12 16:25:32.834] [error] Github同步失败： Error: fatal: not a git repository (or any of the parent directories): .git

    at Object.action (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

目前这个只能可以通过退出然后重新本地同步就行，只是每次都退出和本地同步的话，可能有点麻烦。

**Comment by liuweixu** [comment]
> 对应的同步问题修复后这个问题应该也被修复了，还请更新测试下。

您好，这个问题是解决了，真的很感谢，然而我刚才测试时，发现有个新的问题，就是每次产生新的存档时，就不能自动同步，而云同步这一栏中，如果直接点击同步时，也会出现错误，错误记录为：

[2024-10-12 16:25:01.484] [info]  成功打开游戏 134110077
[2024-10-12 16:25:14.774] [info]  游戏数据已成功更新
[2024-10-12 16:25:15.233] [info]  成功复制游戏 134110077 存档到 C:\Users\weixu\AppData\Roaming\vnite\app\data\games\134110077\saves\2\
[2024-10-12 16:25:15.793] [info]  本地同步完成，app -> sync
[2024-10-12 16:25:15.883] [error] Github同步失败： Error: fatal: not a git repository (or any of the parent directories): .git

    at Object.action (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-10-12 16:25:19.380] [info]  游戏数据已成功更新
[2024-10-12 16:25:19.426] [info]  游戏数据已成功更新
[2024-10-12 16:25:19.636] [info]  游戏数据已成功更新
[2024-10-12 16:25:19.894] [info]  游戏数据已成功更新
[2024-10-12 16:25:24.847] [info]  打开文件夹: C:\Users\weixu\AppData\Roaming\vnite\app\data\games\134110077
[2024-10-12 16:25:32.749] [info]  本地同步完成，app -> sync
[2024-10-12 16:25:32.834] [error] Github同步失败： Error: fatal: not a git repository (or any of the parent directories): .git

    at Object.action (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///E:/Japanese/GALTools/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

目前好像只能通过“退出和重新登录”的方法才能解决，只是每次这样做可能有点麻烦，大佬看看能不能解决一下这个问题？

**Comment by ximu3** [comment]
vnite2会解决这个问题（到时会整个推翻重写一遍，解决掉初期设计导致的问题）

**Comment by liuweixu** [comment]
> vnite2会解决这个问题（到时会整个推翻重写一遍，解决掉初期设计导致的问题）

好的好的，十分感谢大佬。
