### ISSUE TITLE
[Bug]: 游戏状态更新后（存档更新/添加新游戏）Github同步失败

### ISSUE THREAD

**Issue by noselenar** [ximu3/vnite#66]
### 软件版本

1.5.10

### 问题描述

游戏状态更新后（存档更新/添加新游戏）Github同步失败，见图1，日志如下。
通过日志的提示，将'D:\applications\vnite\sync\data\games\708292993\saves\1\SaveData'文件夹删除数次后即可成功同步更新，见图2，原因未知。

### 问题日志

[2024-10-17 02:52:26.840] [error] 本地同步出错，app -> sync: Error: EPERM: operation not permitted, rmdir 'D:\applications\vnite\sync\data\games\708292993\saves\1\SaveData'
[2024-10-17 02:52:26.936] [error] Github同步失败： Error: fatal: not a git repository (or any of the parent directories): .git

    at Object.action (file:///D:/applications/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///D:/applications/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///D:/applications/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///D:/applications/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///D:/applications/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/applications/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### **问题截图1**
![image](https://github.com/user-attachments/assets/a9a3b0a3-41c9-4959-9109-7f5a59ed306f)
### **问题截图2**
![image](https://github.com/user-attachments/assets/acd5c91d-f7be-477b-9f77-ee83e1527db1)

**Comment by noselenar** [comment]
我发现每次commit都是将"~\AppData\Roaming\vnite\app"下的data文件夹和config文件夹复制到"\vnite\sync"文件夹中，然后再进行commit。能否实现将数据文件夹设置为"\vnite\sync"并只进行增量提交呢？这样或许会解决bug，同时能满足版本控制的需求。

**Comment by ximu3** [comment]
v2使用webdav重构了云同步功能，还请更新版本。
