### ISSUE TITLE
[Bug]: 同步云端数据到本地以后，无法同步数据

### ISSUE THREAD

**Issue by MadokaMoonlight** [ximu3/vnite#70]
### 软件版本

1.5.10

### 问题描述

1.当另一台设备同步数据到云端后（初始化仓库），当前设备选择同步数据到本地
2.同步成功以后，点击同步按钮，报错

### 问题日志

[2024-10-17 08:35:07.257] [info]  仓库克隆到 D:\Galgame\vnite\sync
[2024-10-17 08:35:09.007] [info]  本地同步完成，sync -> app
[2024-10-17 08:35:09.008] [info]  使用云端数据初始化仓库成功
[2024-10-17 08:35:09.021] [info]  设置已成功更新
[2024-10-17 08:35:09.091] [info]  游戏数据已成功更新
[2024-10-17 08:35:09.171] [info]  设置已成功更新
[2024-10-17 08:35:43.621] [info]  本地同步完成，app -> sync
[2024-10-17 08:35:43.754] [error] Github同步失败： Error: fatal: not a git repository (or any of the parent directories): .git

    at Object.action (file:///D:/Galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4463:25)
    at PluginStore.exec (file:///D:/Galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///D:/Galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///D:/Galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///D:/Galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/Galgame/vnite/resources/app.asar/node_modules/simple-git/dist/esm/index.js:45:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### 问题截图

![Snipaste_2024-10-17_08-34-40](https://github.com/user-attachments/assets/8e0825eb-96d0-447b-8444-de4ce92e3276)
![Snipaste_2024-10-17_08-35-22](https://github.com/user-attachments/assets/39d8f755-f546-4032-b621-4e79a025ac7a)
![Snipaste_2024-10-17_08-35-51](https://github.com/user-attachments/assets/3caafcff-cb47-4515-a6cd-490287953d65)

**Comment by MadokaMoonlight** [comment]
![Snipaste_2024-10-17_08-41-39](https://github.com/user-attachments/assets/81d679cf-7f41-4745-a481-3685bbf1a13b)
同步按钮

**Comment by ximu3** [comment]
vnite中退出github账号后重新同步。

**Comment by MadokaMoonlight** [comment]
> vnite中退出github账号后重新同步。

但这样会初始化远程仓库，而不是增量同步

**Comment by ximu3** [comment]
v2使用webdav进行云同步，不会出现这个问题，还请更新版本。
