### ISSUE TITLE
[Bug]: 软件处理游戏数据时出现错误

### ISSUE THREAD

**Issue by jianguanying** [ximu3/vnite#71]
### 软件版本

1.5.10

### 问题描述

使用刮削器添加正常填写相关参数后，最后处理游戏数据时出现“[error] 获取游戏数据时出错：TypeError: Cannot read properties of undefined (reading 'game')”

### 问题日志

[2024-10-18 11:49:50.396] [error] Error in organizeGameData: TypeError: Cannot read properties of undefined (reading 'game')
    at organizeGameData (file:///F:/ruanjian/vnite/resources/app.asar/out/main/index.mjs:717:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IpcMainImpl.<anonymous> (file:///F:/ruanjian/vnite/resources/app.asar/out/main/index.mjs:1994:5)

### 问题截图

![无标题](https://github.com/user-attachments/assets/ddd089a1-608f-4f4e-8539-f243a6234f8e)

**Comment by noselenar** [comment]
这个重新获取一遍就ok

**Comment by jianguanying** [comment]
重试了几次也还是这个·界面

**Comment by jianguanying** [comment]
我懂我怎么触发的了，在填写游戏名识别完游戏之后如果不选择对应的游戏最后就会出现这个

**Comment by ximu3** [comment]
> 我懂我怎么触发的了，在填写游戏名识别完游戏之后如果不选择对应的游戏最后就会出现这个
了解了，下个版本会加一个检测来解决这个误操作问题。
